### ISSUE TITLE
一部環境でgoogle is not definedのerrorになる

### ISSUE THREAD

**Issue by HARUKINEMA** [HARUKINEMA/ki-wi#41]
手の出しようがないので一旦諦めます
isseiのwin及びスマホ(wifi)でのみ(及びHARUKINEMAのスマホ(wifi切り替え時に一瞬だけ))該当エラー確認
他の人のwinだと見えるようです
カニが出ないのはブラウザかOSの設定で位置情報をONにしていないからだと思われる

**Comment by Issei0804-ie** [comment]
https://github.com/HARUKINEMA/ki-wi/pull/73

error自体は消したので close します
